version: "3"
services:

  db:
    image: library/mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: kilsundvaeret
  met-proxy:
    image: bentsolheim/met-proxy:latest
    ports:
      - "9010:9010"